# Site settings
title: 三十二张机的博客
email: zvtibo2012@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
github_username:  zvtibo

# Build settings
markdown: kramdown

paginate: 5
