# Site settings
title: 三十二机的博客
email: zvtibo2012@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zvtibo.github.io/" # the base hostname & protocol for your site
github_username:  zvtibo

# Build settings
markdown: kramdown

comments:
  provider: duoshuo
  duoshuo:
    short_name: zvtibo
